packages:
  - apps/api
  - apps/web
  - packages/*

allowBuilds:
  esbuild: true
  msgpackr-extract: true
  workerd: true
  sharp: true
  bufferutil: true
  utf-8-validate: true
  "@clerk/shared": false

minimumReleaseAgeExclude:
  - effect@4.0.0-beta.84
  - "@effect/vitest@4.0.0-beta.84"
